version: '3.7'
services:
  mysqldatabase:
    image: mysql:8.0.23
    ports:
      - 3307:3306
    networks:
      - mysqlnetwork
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prodyna_market
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword

  prodyna_application:
    image: mostafabakr/prodyna_market:4.0
    restart: on-failure
    depends_on:
      - mysqldatabase
    ports:
      - 8081:8081
    networks:
      - mysqlnetwork
    command: ./docker-entrypoint.sh #doesnt work check!
    environment:
      DATABASE_HOST: mysqldatabase
      DATABASE_USER: springuser
      DATABASE_PASSWORD: ThePassword
      DATABASE_NAME: prodyna_market
      DATABASE_PORT: 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldatabase:3306/prodyna_market 
#      MYSQL_HOST: mysqldatabase
#      MYSQL_USER: springuser
#      MYSQL_PASSWORD: ThePassword
#      MYSQL_DB: prodyna_market

networks:
  mysqlnetwork:

volumes:
  db-data:
    driver: local